clab-vios-lab-vios1:
    hostname: 192.168.106.3
    platform: ios
    groups:
        - cisco_ios_xe
    data:
        role: edge
        site: NYC

clab-vios-lab-vios2:
    hostname: 192.168.106.4
    platform: ios
    groups:
        - cisco_ios_xe
    data:
        role: ISP
        site: NYC
